### ISSUE TITLE
Report output truncated

### ISSUE THREAD

**Issue by jmr-ua-pt** [cayhorstmann/ltihub#2]
I created a LTIHub assignment with Python exercises (https://play.codecheck.ws/lti/assignment?id=430)
and when I press "Submit query" on an exercise, the table with the error/output report seems truncated after a few lines and has no scrollbar to allow viewing the rest.  This is quite serious: it make it unusable.

Here goes a screenshot:

![image](https://user-images.githubusercontent.com/6420928/92471063-39e42a00-f1cf-11ea-9ef8-a877413babc5.png)

Back in July I used other LTIu assignments with no problem.

I'm using firefox.  Changing the window size or zoom in the browser changes the amount of output visible.

**Comment by cayhorstmann** [comment]
Thanks, that was caused by a change in CodeCheck. I made it so that scroll bars are added if necessary.

**Comment by jmr-ua-pt** [comment]
Thanks a lot for the quick fix.
I confirm that it seems to be fixed.

However, when "Viewing submissions" as Instructor the scrollbars are still missing.  I opened a new issue for that.
